### ISSUE TITLE
Redirects to /sessions/null/sessions/init/reverseproxyauth

### ISSUE THREAD

**Issue by girgen** [trajano/reverse-proxy-auth-sonar-plugin#5]
Hi!

I'm trying to get the reverse-proxy-auth-sonar-plugin working. When clicking the Log-in link, I can see in the access log:

```
"GET /sessions/new?return_to=%2F HTTP/1.1" 302
"GET /sessions/null/sessions/init/reverseproxyauth HTTP/1.1" 404
```

Any ideas what's wrong here? Latest code from master, and sonarqube 6.1. All I did was build the plugin, copy the one jar into extensions/plugins directory and add `sonar.security.realm=reverseproxyauth` to the `sonar.properties` file.

BTW, what is the suggested configuration of apache for the plugin to work? There are no suggestions about this, would be great with a few lines in the readme.

I'm using shibboleth for authentication, BTW.

Thanks,
Palle

**Comment by trajano** [comment]
Hmm, I know how to fix the error, but for now can you see if you can set the prefix to "/" and see if it works in your sonar.properties

**Comment by trajano** [comment]
Sorry looking further into the code, the work around should be setting your server base URL.

**Comment by trajano** [comment]
I'm using SSL Client Certs for my authentication so it's not really a simple configuration that be put in.

**Comment by trajano** [comment]
I created a release 6.0.1

**Comment by girgen** [comment]
OK. Cool. I'm using SAML2 (Shibboleth). I guess something like this will transfer REMOTE_USER to sonarqube:

```
                RewriteEngine On
                RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
                RequestHeader set X-Forwarded-User "‰{REMOTE_USER}e"
```

**Comment by girgen** [comment]
Hi!

It's not clear to me what you mean by "setting your server base URL"?

And just for clarity, the proxy apache is on another machine, one with Internet access, whereas the sonarqube is on a private network.

My apache config is something along the line of 

```
    <Proxy "*">
        AuthType shibboleth
        ShibRequestSetting applicationId sonarqube
        #  require shibboleth staff@example.com
        <RequireAll>
            ShibRequestSetting requireSession 1
            Require valid-user
            Require shib-attr affiliation staff@example.com
        </RequireAll>

        RewriteEngine On
        RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
        RequestHeader set X-Forwarded-User "%{REMOTE_USER}e"
    </Proxy>

    RequestHeader unset Authorization

    ProxyRequests Off
    ProxyPreserveHost   On

    ProxyPass           / http://192.168.1.7:9000/ connectiontimeout=240 timeout=1200
    ProxyPassReverse    / http://192.168.1.7:9000/
```

 and i sonarqube, I just added

```
sonar.security.realm=reverseproxyauth
```

and here's what I get in the logs:

```
192.168.1.244 - - [31/okt/2016:22:18:15 +0100] "GET /sessions/new?return_to=%2F HTTP/1.1" 302 - "https://sonarqube.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
192.168.1.244 - - [31/okt/2016:22:18:15 +0100] "GET /sessions/init/reverseproxyauth HTTP/1.1" 302 - "https://sonarqube.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"

==> logs/sonar.log <==
2016.10.31 22:18:15 ERROR web[][o.s.s.a.AuthenticationError] Fail to initialize authentication with provider 'reverseproxyauth'
org.sonar.server.exceptions.BadRequestException: user.bad_login
        at org.sonar.server.user.UserUpdater.createNewUserDto(UserUpdater.java:213) ~[sonar-server-6.1.jar:na]
        at org.sonar.server.user.UserUpdater.create(UserUpdater.java:98) ~[sonar-server-6.1.jar:na]
        at org.sonar.server.authentication.UserIdentityAuthenticator.registerNewUser(UserIdentityAuthenticator.java:92) ~[sonar-server-6.1.jar:na]
        at org.sonar.server.authentication.UserIdentityAuthenticator.register(UserIdentityAuthenticator.java:74) ~[sonar-server-6.1.jar:na]
        at org.sonar.server.authentication.UserIdentityAuthenticator.authenticate(UserIdentityAuthenticator.java:62) ~[sonar-server-6.1.jar:na]
        at org.sonar.server.authentication.BaseContextFactory$ContextImpl.authenticate(BaseContextFactory.java:81) ~[sonar-server-6.1.jar:na]
        at net.trajano.sonar.plugins.reverseproxyauth.ReverseProxyAuthUsersIdentityProvider.init(ReverseProxyAuthUsersIdentityProvider.java:95) ~[na:na]
        at org.sonar.server.authentication.InitFilter.doFilter(InitFilter.java:73) ~[sonar-server-6.1.jar:na]
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126) [sonar-server-6.1.jar:na]
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95) [sonar-server-6.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:60) [sonar-server-6.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.sonar.server.platform.web.RoutesFilter.doFilter(RoutesFilter.java:55) [sonar-server-6.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:113) [sonar-server-6.1.jar:na]
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:81) [sonar-server-6.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:191) [logback-access-1.1.3.jar:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.32.jar:8.0.32]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

==> logs/access.log <==
192.168.1.244 - - [31/okt/2016:22:18:15 +0100] "GET /sessions/unauthorized HTTP/1.1" 200 2643 "https://sonarqube.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
```

**Comment by trajano** [comment]
6.0.1 does not require the workaround of setting the server base URL anymore.

**Comment by girgen** [comment]
OK, so what can be wrong with the config, see above, running 6.0.1.

```
2016.10.31 22:18:15 ERROR web[][o.s.s.a.AuthenticationError] Fail to initialize authentication with provider 'reverseproxyauth'
org.sonar.server.exceptions.BadRequestException: user.bad_login
```

**Comment by trajano** [comment]
Did you allow new users to be created?  It's normally on by default.

**Comment by girgen** [comment]
It's a vanilla system. Just freshly installed.

**Comment by girgen** [comment]
After fixing a bug in my apache config, it works like a charm. 

`RequestHeader set X-Forwarded-User "%{PROXY_USER}e"` (I had REMOTE_USER there).

I really think this project would gain from some simple examples how to configure the web server. Not all proxy configs use `X-Forwarded-User`, I hade to check the code to make sure that was the header to use. Apart from that it seems to work great for us. Thanks!

**Comment by trajano** [comment]
`PROXY_USER` is a specific thing for your security proxy implementation.
There's no need to use `X-Fowarded-User` either, that's configurable.  I'll
open up the wiki to put my SSL Client Side cert example.  However, like
yours it's pretty specific.

**Comment by girgen** [comment]
Ok, cool. Anyway, it works. Thanks!
