### ISSUE TITLE
Problem running teamcity + sonarqube + reverse-proxy-auth-sonar-plugin

### ISSUE THREAD

**Issue by girgen** [trajano/reverse-proxy-auth-sonar-plugin#7]
Hi.

After successfully getting sonarqube running with the this plugin (thanks for the great and quick help!), we now try to let Team City (TC) connect to SonarQube (SQ). TC does some peculiar things. It fetches all of SQs plugins and tries to load them in a separate classloader on the TC. This fails for the reverse-proxy-auth-sonar-plugin since some classes in javax.serlvet are not loaded.

This is of course not really a problem in the reverse proxy plugin, but perhaps someone using the plugin has seen this and found a solution, like where to add a jar for TCs SQ-plugin classloader?

Thanks,
Palle
```
[21:58:06] :	 [Step 3/3] 21:58:06.917 DEBUG - GET 200 http://192.168.1.7:9000/deploy/plugins/index.txt | time=8ms

[...]

[21:58:07] :	 [Step 3/3] 21:58:07.359 DEBUG - Load plugins (done) | time=441ms
[21:58:07] :	 [Step 3/3] 21:58:07.615 DEBUG - API compatibility mode is enabled on plugin Git [scmgit] (built with API lower than 5.2)
[21:58:07] :	 [Step 3/3] 21:58:07.616 DEBUG - API compatibility mode is enabled on plugin SVN [scmsvn] (built with API lower than 5.2)
[21:58:07] :	 [Step 3/3] 21:58:07.718 DEBUG - Plugins:
[21:58:07] :	 [Step 3/3] 21:58:07.718 DEBUG -   * Findbugs 3.4.3 (findbugs)
[21:58:07] :	 [Step 3/3] 21:58:07.718 DEBUG -   * Java 4.2.1.6971 (java)
[21:58:07] :	 [Step 3/3] 21:58:07.719 DEBUG -   * Git 1.2 (scmgit)
[21:58:07] :	 [Step 3/3] 21:58:07.719 DEBUG -   * SVN 1.3 (scmsvn)
[21:58:07] :	 [Step 3/3] 21:58:07.719 DEBUG -   * Reverse Proxy Authenticator 6.0.1 (reverseproxyauth)
[21:58:07] :	 [Step 3/3] 21:58:07.719 DEBUG -   * JavaScript 2.17.0.3154 (javascript)
[21:58:07] :	 [Step 3/3] INFO: ------------------------------------------------------------------------
[21:58:07] :	 [Step 3/3] INFO: EXECUTION FAILURE
[21:58:07] :	 [Step 3/3] INFO: ------------------------------------------------------------------------
[21:58:07] :	 [Step 3/3] Total time: 2.758s
[21:58:08] :	 [Step 3/3] Final Memory: 18M/1472M
[21:58:08]W:	 [Step 3/3] ERROR: Error during Sonar runner execution
[21:58:08] :	 [Step 3/3] INFO: ------------------------------------------------------------------------
[21:58:08]W:	 [Step 3/3] org.sonar.runner.impl.RunnerException: Unable to execute Sonar
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
[21:58:08]W:	 [Step 3/3] 	at java.security.AccessController.doPrivileged(Native Method)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.api.Runner.execute(Runner.java:100)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.Main.executeTask(Main.java:70)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.Main.execute(Main.java:59)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.Main.main(Main.java:53)
[21:58:08]W:	 [Step 3/3] Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter
[21:58:08]W:	 [Step 3/3] 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:58:08]W:	 [Step 3/3] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[21:58:08]W:	 [Step 3/3] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[21:58:08]W:	 [Step 3/3] 	at java.security.AccessController.doPrivileged(Native Method)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.IsolatedClassloader.loadClass(IsolatedClassloader.java:94)
[21:58:08]W:	 [Step 3/3] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:84)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.DefaultClassloaderRef.loadClassIfPresent(DefaultClassloaderRef.java:40)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClassFromParent(ClassRealm.java:147)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:35)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
[21:58:08]W:	 [Step 3/3] 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:58:08]W:	 [Step 3/3] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[21:58:08]W:	 [Step 3/3] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[21:58:08]W:	 [Step 3/3] 	at java.security.AccessController.doPrivileged(Native Method)
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
[21:58:08]W:	 [Step 3/3] 	at net.trajano.sonar.plugins.reverseproxyauth.ReverseProxyAuthPlugin.define(ReverseProxyAuthPlugin.java:37)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:55)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.scanner.task.TaskContainer.addTaskExtensions(TaskContainer.java:62)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.scanner.task.TaskContainer.doBeforeStart(TaskContainer.java:49)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:140)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:78)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
[21:58:08]W:	 [Step 3/3] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:58:08]W:	 [Step 3/3] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:58:08]W:	 [Step 3/3] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:58:08]W:	 [Step 3/3] 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
[21:58:08]W:	 [Step 3/3] 	... 9 more
[21:58:08]W:	 [Step 3/3] Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
[21:58:08]W:	 [Step 3/3] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[21:58:08]W:	 [Step 3/3] 	at org.sonar.runner.impl.IsolatedClassloader.loadClass(IsolatedClassloader.java:94)
[21:58:08]W:	 [Step 3/3] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:58:08]W:	 [Step 3/3] 	... 55 more
[21:58:08]W:	 [Step 3/3] Process exited with code 1
[21:58:08]E:	 [Step 3/3] Step SonarQube Runner failed
```

**Comment by trajano** [comment]
Can you try with the current version, I had redone the dependencies so it shouldn't be an issue anymore.

**Comment by trajano** [comment]
Closing due to lack of response
